#!/bin/sh
echo Downloading Qt
INSTALLER=qt-opensource-linux-x64-5.13.0.run
ENVFILE=qt-5.13.0.env
export QT_CI_PACKAGES="qt.qt5.5130.gcc_64,qt.qt5.5130.qtwebengine"
echo Installing Qt
echo "Selected ${QT_CI_PACKAGES} packages"
./extract-qt-installer $PWD/$INSTALLER /home/root/Qt
echo Create $ENVFILE
cat << EOF > $ENVFILE

EOF
