//
// Created by leixiao on 2019/7/12.
//

#ifndef MINIPREMIERE_UPDATEVIEWNOTIFICATION_H
#define MINIPREMIERE_UPDATEVIEWNOTIFICATION_H


class UpdateViewNotification {

};


#endif //MINIPREMIERE_UPDATEVIEWNOTIFICATION_H
